/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteRewardsRouteImport } from './routes/_site.rewards'
import { Route as SiteMenuRouteImport } from './routes/_site.menu'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCateringRouteImport } from './routes/_site.catering'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRewardsRoute = SiteRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCateringRoute = SiteCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/about': typeof SiteAboutRoute
  '/catering': typeof SiteCateringRoute
  '/checkout': typeof SiteCheckoutRoute
  '/menu': typeof SiteMenuRoute
  '/rewards': typeof SiteRewardsRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/about': typeof SiteAboutRoute
  '/catering': typeof SiteCateringRoute
  '/checkout': typeof SiteCheckoutRoute
  '/menu': typeof SiteMenuRoute
  '/rewards': typeof SiteRewardsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/catering': typeof SiteCateringRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/menu': typeof SiteMenuRoute
  '/_site/rewards': typeof SiteRewardsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/catering'
    | '/checkout'
    | '/menu'
    | '/rewards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/catering'
    | '/checkout'
    | '/menu'
    | '/rewards'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/about'
    | '/_site/catering'
    | '/_site/checkout'
    | '/_site/menu'
    | '/_site/rewards'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/rewards': {
      id: '/_site/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof SiteRewardsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/menu': {
      id: '/_site/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/catering': {
      id: '/_site/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof SiteCateringRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteCateringRoute: typeof SiteCateringRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SiteRewardsRoute: typeof SiteRewardsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteCateringRoute: SiteCateringRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteMenuRoute: SiteMenuRoute,
  SiteRewardsRoute: SiteRewardsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
